### ISSUE TITLE
Provide a framework for sending messages, which supports SMS, WhatsApp, internal messages 

### ISSUE THREAD

**Issue by alberto56** [dcycle/starterkit-node#65]

**Comment by alberto56** [comment]
Get the latest master branch of https://github.com/dcycle/starterkit-node

./scripts/deploy.sh 

It is currently possible to send messages in three (3) different ways:

## 1. by whatsapp

./scripts/node-cli.sh

await app.c('whatsAppSend').parsepropertySendMessage('{"message": "This is a test message", "sendTo":"+150XXXXXXX"}');

## 2. by sms

./scripts/node-cli.sh

await app.c('sendSMS').parsepropertySendSMS('{"message": "This is a test message", "sendTo":"+150XXXXXXX"}');

## 3. internally

./scripts/node-cli.sh

await app.c('chat').addMessage({"name": "This is a name", "message":"this is a message"});

If you use ./scripts/uli.sh to log into the system you will see the latest message appear.

## What we want to do

Take a look at the modules ./app/code/chatbot and ./app/code/chatbotCalculator. These show the kind of framework we want to implement for texting.

In the case of chatbot, we have in ./app/config/versioned.yml:

    ./chatbot/index.js:
      plugins:
        calculator:
          name: calculator
          plugin: chatbotCalculator

We want to have four (4) new modules:

* textFramework
* textFrameworkWhatsApp
* textFrameworkSMS
* textFrameworkInternal

In our ./app/config/versioned.yml file, we want to have something like:

    ./textFramework/index.js:
      plugins:
        whatsapp:
          name: whatsapp
          plugin: textFrameworkWhatsApp
        sms:
          name: sms
          plugin: textFrameworkSMS
        internal:
          name: internal
          plugin: textFrameworkInternal

Similarly to how the chatbot module has:

    chat({plugin: "calculator", text: "5+5"});

We want our textFramework to be able to do the following:

    await sendText({
      plugin: whatsapp,
      message: 'hello',
      sendTo: '+15555555555',
    });
    await sendText({
      plugin: sms,
      message: 'hello',
      sendTo: '+15555555555',
    });
    await sendText({
      plugin: internal,
      message: 'hello',
      name: 'my name',
    });

If the plugins have missing information, an error is thrown:

    await sendText({
      plugin: internal,
      message: 'hello',
      sendTo: '+15555555555',
    });

will result in error: missing "name" parameter.

    await sendText({
      plugin: sms,
      message: 'hello',
      name: 'my name',
    });

will result in error: missing sendTo parameter

## Do not change the existing modules

The existing whatsAppSend, sendSms, and chat modules should remain unchanged.

We want new modules,

* textFrameworkWhatsApp
* textFrameworkSMS
* textFrameworkInternal

to exist as GLUE between the textFramework modules and the existing modules

## Long-term goal

The long-term goal will be to have a system where it's possible to add a new plugin such as Signal, or Messenger, or other.

**Comment by suresh-kumara-gist** [comment]
await app.c('textFramework').sendText({plugin: 'sms', message: 'hello', sendTo: '+919632324012' }) 

await app.c('textFramework').sendText({plugin: 'whatsapp', message: 'hello', sendTo: '+919632324012' })

await app.c('textFramework').sendText({plugin: 'internal', message: 'hello', name: 'my name' })

await app.c('textFramework').sendText({ })

await app.c('textFramework').sendText({ plugin: 'sms' })
await app.c('textFramework').sendText({ plugin: 'whatsapp' })
await app.c('textFramework').sendText({ plugin: 'internal' })

await app.c('textFramework').sendText({ plugin: 'sms', message: 'hello' })
await app.c('textFramework').sendText({ plugin: 'whatsapp', message: 'hello' })
await app.c('textFramework').sendText({ plugin: 'internal', message: 'hello' })


await app.c('textFramework').sendText({ plugin: 'sms', sendTo: '+919632324012' })
await app.c('textFramework').sendText({ plugin: 'whatsapp', sendTo: '+919632324012'})
await app.c('textFramework').sendText({ plugin: 'internal', sendTo: '+919632324012'})
